### ISSUE TITLE
Building Error

### ISSUE THREAD

**Issue by MaboroshiChan** [facebook/Haxl#124]
When I was trying to build the Haxl-2.3.0.0 using stack, I got this error message.
The version of GHC for building this is 8.8.3
```
Haxl\Core\Exception.hs:303:20: error:
haxl                >     Ambiguous occurrence `MonadFail'
haxl                >     It could refer to
haxl                >        either `Prelude.MonadFail',
haxl                >               imported from `Prelude' at Haxl\Core\Exception.hs:31:8-26
haxl                >               (and originally defined in `Control.Monad.Fail')
haxl                >            or `Haxl.Core.Exception.MonadFail',
```
haxl                >               defined at Haxl\Core\Exception.hs:300:1

**Comment by watashi** [comment]
This issue has already been addressed by https://github.com/facebook/Haxl/commit/2d3731ec7a9959c19f74baa5613ed1a3363ab798

@simonmar we need a release on hackage.
