### ISSUE TITLE
New version to Hackage for GHC 8.8 and beyond

### ISSUE THREAD

**Issue by neurogoo** [facebook/Haxl#133]
Hi,

Sorry to bother, but is there any plans on releasing a new version to Hackage as the current highest version 2.1.2.0 doesn't work on ghc 8.8?

**Comment by DylanZA** [comment]
there is a candidate release here: https://hackage.haskell.org/package/haxl-2.3.0.0/candidate
can you try that out?

**Comment by neurogoo** [comment]
Hi, thanks! I did give it a quick spin and didn't find any problems 👍

**Comment by simonmar** [comment]
Now published: https://hackage.haskell.org/package/haxl-2.3.0.0
