### ISSUE TITLE
using haxl for data sources where dependencies are not statically known

### ISSUE THREAD

**Issue by mwotton** [facebook/Haxl#30]
I have a learning algorithm that chooses variables to make decisions on that i'm trying to integrate into my Haxl-based project. The snag here is that the learning alg chooses those variable dynamically, making it hard to write a datasource that doesn't just fetch everything it might look at.

I think I can see a way around this using template haskell and introspecting on the generated decision tree, but if I'm overcomplicating it I'd love to hear about it.

**Comment by simonmar** [comment]
I'm not sure I understand enough about your use case to comment.  Could you give some example types to give more context?

**Comment by simonmar** [comment]
Going to close this out because I'm not sure how we can make progress, feel free to re-open if you have more info.

**Comment by mwotton** [comment]
It was an ill-formed question :) as I learned more I worked out how to do it.
