### ISSUE TITLE
Real World SQL API

### ISSUE THREAD

**Issue by chadbrewbaker** [facebook/Haxl#35]
I'm trying to get Haxl running against a real database from the sql example.

Is this the only function you need to implement?

sql :: SQLResult a => String -> IO a

Browsing this example it seems the user of the library keeps track of the DB connection pool, not Haxl?

**Comment by simonmar** [comment]
You can find a more complete example that uses sqlite here: https://github.com/simonmar/fpdays14/blob/master/BlogDataSource/Internals2.hs
