### ISSUE TITLE
Can equal Requests be sent in same round of fetch?

### ISSUE THREAD

**Issue by sopvop** [facebook/Haxl#36]
From documentation it is clear that fetch requests are cached between rounds of fetch. But It is not clear (at least for me) if DataSource fetch can get more than one equal Requests. For example
~~~~.haskell
data SqlRequest a where
    RequestComments :: PostId -> SqlRequest [Comment]

instance DataSource () SqlRequest where
   fetch state _ _ fetches =  -- can fetches here contain more than one RequestComments to same PostId?
~~~~

**Comment by simonmar** [comment]
The `fetch` method should never see multiple identical requests.
