### ISSUE TITLE
Alternative Typeclass Implementation?

### ISSUE THREAD

**Issue by jqyu** [facebook/Haxl#43]
Pardon my ignorance if there's an obvious reason not to do this, I'm really new to functional programming, but I was playing around with porting Haxl to different environments (in particular, Purescript to try to ease in the nodejs community to the idea), and I realized that it's pretty straightforward to implement a `<|>` operator. This implementation is Purescript so I'm not sure how well it translates to real Haskell

https://github.com/jqyu/purescript-rad/blob/master/src/Rad/Core/Monad.purs#L236-L243

I don't know much about the Haskell runtime but I suppose the fact that it's a recursive implementation may make memory bounds hard to predict, but this allows for a graceful way of recovering from errors, as well as straightforward implementations of retried requests (i.e., chaining a fixed number of `<|>` calls to catch failures)

In particular, I'm working on a GraphQL implementation using Haxl and it would be really useful for me to be able to catch errors and return a null result for a branch of a query so I figured other people might be able to benefit from this as well.

**Comment by JonCoens** [comment]
<|> could be fairly straight-forward, but doesn't fully fit in with our intended exception semantics. We use withDefault more to ensure that CriticalErrors bubble up appropriately when the framework fails.

https://github.com/facebook/Haxl/blob/master/Haxl/Prelude.hs#L198-L203

<|> will also not save you from pure exceptions in code (someone calls error).
Is there a use-case that fits using an implementation of <|> over withDefault?

**Comment by jqyu** [comment]
On closer inspection it looks like `withDefault` and `catchAny` cover all my use cases, I just need to restructure some of my own code.

Thanks for addressing this!

**Comment by simonmar** [comment]
Ok, I'm going to go ahead and close this. @jqyu thanks for bringing it up, and let us know if there's anything else we can help with.
