### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [facebook/Haxl#52]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like _Haxl_, deleted their software history.

https://github.com/facebook/Haxl/commit/74a3874f0b0a83e4f3c90c1455a37b9d17f2ead7

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask Haxl developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by simonmar** [comment]
We have the history internally, but it was not exposed when open-sourcing the project due to the effort it would have taken to manually edit all the history to remove information that was internal and mostly irrelevant to open-source users.  I don't think the lack of history for this project is a barrier to using it.

**Comment by gustavopinto** [comment]
Hi @simonmar, 

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo
