### ISSUE TITLE
Missing test file: sigma/haxl/core/tests/LoadCache.txt

### ISSUE THREAD

**Issue by phadej** [facebook/Haxl#55]
Missing test file:

```hs
tests/TestExampleDataSource.hs:  loadcache <- readFile "sigma/haxl/core/tests/LoadCache.txt"
```

**Comment by niteria** [comment]
Are you rebased after https://github.com/facebook/Haxl/commit/18935515643e4d989be8e35bd0c3149de138a5a5? That path doesn't occur in the source anymore.

**Comment by phadej** [comment]
my bad.
