### ISSUE TITLE
This package is not licensed under BSD3

### ISSUE THREAD

**Issue by peti** [facebook/Haxl#67]
The Cabal file declares this code to be licensed under the BSD-3-Clause license, but that is actually not the case. The code is licensed under BSD3 plus Facebook's "patent termination clause", which is an entirely different thing.

**Comment by simonmar** [comment]
Please see this FAQ: https://code.facebook.com/pages/850928938376556

**Comment by peti** [comment]
???

The document you link to pretty much confirms my point by referring to your license as "Facebook BSD+Patents license". Note that it's *not* saying "BSD3". So I'm not sure how that FAQ should address my concerns. The Cabal file of this package does not correctly identify its license.
