### ISSUE TITLE
Haxl 2 release on Hackage

### ISSUE THREAD

**Issue by fishtreesugar** [facebook/Haxl#86]

**Comment by simonmar** [comment]
Yes, I need to do this. Thanks for the reminder!

**Comment by lorenzo** [comment]
Gentle reminder :)

**Comment by simonmar** [comment]
https://hackage.haskell.org/package/haxl-2.0.0.0

Sorry for the delay - I had planned to write a blog post to accompany the release but I don't seem to be getting around to it, so I'll go ahead and just upload it.
