### ISSUE TITLE
Broken Hackage links

### ISSUE THREAD

**Issue by hamishdickson** [facebook/Haxl#89]
I'm not sure if this is the right place to report this, but with the new Haxl release there are a couple of broken links in hackage:

- https://hackage.haskell.org/package/haxl-2.0.0.0/haxl-2.0.0.0/srcexample/sql/readme.md
- https://hackage.haskell.org/package/haxl-2.0.0.0/haxl-2.0.0.0/srcexample/facebook/readme.md

I am happy to raise a PR if needed

**Comment by simonmar** [comment]
Hmm, good point. These links were written to work from the github repo: https://github.com/facebook/Haxl but they break on Hackage. Perhaps we should just use absolute URLs to github.
