### ISSUE TITLE
Don't rely on `Show` to be valid Haskell code

### ISSUE THREAD

**Issue by alexbiehl** [facebook/Haxl#95]
`dumpCacheAsHaskell` is a neat thing. Unfortunately this relies on the fact that `Show` emits valid code. Not always are the instances under control of the developer. Just recently I tried to `dumpCacheAsHaskell` with types from the `time` library which resulted in invalid Haskell code being generated.

Could we introduce a new type class, maybe with a default implementation for types that are showable?

**Comment by watashi** [comment]
There is a `insertWithShow` function in which you can pass custom functions to show the request and result in `dumpCacheAsHaskell`. Does this solve your problem?

https://github.com/facebook/Haxl/blob/c1c789a71f315e4fd395d5809fe822cdc38b4ca9/Haxl/Core/DataCache.hs#L81

**Comment by alexbiehl** [comment]
Interesting! And I see there is also `dataFetchWithShow`. That would be the one I need, right?

**Comment by watashi** [comment]
Yes, exactly.

**Comment by alexbiehl** [comment]
Thanks this helped!
